export const products = [
  {
    id: '1',
    name: 'Product 1',
    description: 'Description for product 1',
    price: 489,
    stock: 30,
    category: 'Electronics',
    availableSince: '2019-12-31',
    active: false,
  },
  {
    id: '2',
    name: 'Product 2',
    description: 'Description for product 2',
    price: 82,
    stock: 54,
    category: 'Books',
    availableSince: '2020-02-01',
    active: true,
  },
  {
    id: '3',
    name: 'Product 3',
    description: 'Description for product 3',
    price: 209,
    stock: 74,
    category: 'Clothing',
    availableSince: '2020-03-02',
    active: true,
  },
  {
    id: '4',
    name: 'Product 4',
    description: 'Description for product 4',
    price: 276,
    stock: 53,
    category: 'Home Appliances',
    availableSince: '2020-04-03',
    active: false,
  },
  {
    id: '5',
    name: 'Product 5',
    description: 'Description for product 5',
    price: 162,
    stock: 98,
    category: 'Electronics',
    availableSince: '2020-05-04',
    active: true,
  },
  {
    id: '6',
    name: 'Product 6',
    description: 'Description for product 6',
    price: 26,
    stock: 99,
    category: 'Books',
    availableSince: '2020-06-05',
    active: true,
  },
  {
    id: '7',
    name: 'Product 7',
    description: 'Description for product 7',
    price: 231,
    stock: 54,
    category: 'Clothing',
    availableSince: '2020-07-06',
    active: true,
  },
  {
    id: '8',
    name: 'Product 8',
    description: 'Description for product 8',
    price: 417,
    stock: 85,
    category: 'Home Appliances',
    availableSince: '2020-08-07',
    active: false,
  },
  {
    id: '9',
    name: 'Product 9',
    description: 'Description for product 9',
    price: 341,
    stock: 39,
    category: 'Electronics',
    availableSince: '2020-09-08',
    active: true,
  },
  {
    id: '10',
    name: 'Product 10',
    description: 'Description for product 10',
    price: 327,
    stock: 22,
    category: 'Books',
    availableSince: '2020-10-09',
    active: false,
  },
  {
    id: '11',
    name: 'Product 11',
    description: 'Description for product 11',
    price: 22,
    stock: 32,
    category: 'Clothing',
    availableSince: '2020-11-10',
    active: true,
  },
  {
    id: '12',
    name: 'Product 12',
    description: 'Description for product 12',
    price: 205,
    stock: 65,
    category: 'Home Appliances',
    availableSince: '2020-12-11',
    active: false,
  },
  {
    id: '13',
    name: 'Product 13',
    description: 'Description for product 13',
    price: 409,
    stock: 96,
    category: 'Electronics',
    availableSince: '2020-01-12',
    active: false,
  },
  {
    id: '14',
    name: 'Product 14',
    description: 'Description for product 14',
    price: 458,
    stock: 37,
    category: 'Books',
    availableSince: '2020-02-13',
    active: true,
  },
  {
    id: '15',
    name: 'Product 15',
    description: 'Description for product 15',
    price: 337,
    stock: 22,
    category: 'Clothing',
    availableSince: '2020-03-14',
    active: true,
  },
  {
    id: '16',
    name: 'Product 16',
    description: 'Description for product 16',
    price: 155,
    stock: 65,
    category: 'Home Appliances',
    availableSince: '2020-04-15',
    active: false,
  },
  {
    id: '17',
    name: 'Product 17',
    description: 'Description for product 17',
    price: 166,
    stock: 6,
    category: 'Electronics',
    availableSince: '2020-05-16',
    active: true,
  },
  {
    id: '18',
    name: 'Product 18',
    description: 'Description for product 18',
    price: 4,
    stock: 53,
    category: 'Books',
    availableSince: '2020-06-17',
    active: true,
  },
  {
    id: '19',
    name: 'Product 19',
    description: 'Description for product 19',
    price: 494,
    stock: 39,
    category: 'Clothing',
    availableSince: '2020-07-18',
    active: false,
  },
  {
    id: '20',
    name: 'Product 20',
    description: 'Description for product 20',
    price: 239,
    stock: 67,
    category: 'Home Appliances',
    availableSince: '2020-08-19',
    active: true,
  },
  {
    id: '21',
    name: 'Product 21',
    description: 'Description for product 21',
    price: 53,
    stock: 96,
    category: 'Electronics',
    availableSince: '2020-09-20',
    active: false,
  },
  {
    id: '22',
    name: 'Product 22',
    description: 'Description for product 22',
    price: 368,
    stock: 25,
    category: 'Books',
    availableSince: '2020-10-21',
    active: false,
  },
  {
    id: '23',
    name: 'Product 23',
    description: 'Description for product 23',
    price: 102,
    stock: 62,
    category: 'Clothing',
    availableSince: '2020-11-22',
    active: true,
  },
  {
    id: '24',
    name: 'Product 24',
    description: 'Description for product 24',
    price: 189,
    stock: 2,
    category: 'Home Appliances',
    availableSince: '2020-12-23',
    active: true,
  },
  {
    id: '25',
    name: 'Product 25',
    description: 'Description for product 25',
    price: 3,
    stock: 75,
    category: 'Electronics',
    availableSince: '2020-01-24',
    active: false,
  },
  {
    id: '26',
    name: 'Product 26',
    description: 'Description for product 26',
    price: 133,
    stock: 32,
    category: 'Books',
    availableSince: '2020-02-25',
    active: true,
  },
  {
    id: '27',
    name: 'Product 27',
    description: 'Description for product 27',
    price: 472,
    stock: 30,
    category: 'Clothing',
    availableSince: '2020-03-26',
    active: true,
  },
  {
    id: '28',
    name: 'Product 28',
    description: 'Description for product 28',
    price: 476,
    stock: 24,
    category: 'Home Appliances',
    availableSince: '2020-04-27',
    active: true,
  },
  {
    id: '29',
    name: 'Product 29',
    description: 'Description for product 29',
    price: 281,
    stock: 43,
    category: 'Electronics',
    availableSince: '2020-04-30',
    active: false,
  },
  {
    id: '30',
    name: 'Product 30',
    description: 'Description for product 30',
    price: 399,
    stock: 56,
    category: 'Books',
    availableSince: '2020-06-01',
    active: true,
  },
  {
    id: '31',
    name: 'Product 31',
    description: 'Description for product 31',
    price: 365,
    stock: 14,
    category: 'Clothing',
    availableSince: '2020-07-02',
    active: true,
  },
  {
    id: '32',
    name: 'Product 32',
    description: 'Description for product 32',
    price: 274,
    stock: 5,
    category: 'Home Appliances',
    availableSince: '2020-08-03',
    active: false,
  },
  {
    id: '33',
    name: 'Product 33',
    description: 'Description for product 33',
    price: 20,
    stock: 32,
    category: 'Electronics',
    availableSince: '2020-09-04',
    active: true,
  },
  {
    id: '34',
    name: 'Product 34',
    description: 'Description for product 34',
    price: 182,
    stock: 23,
    category: 'Books',
    availableSince: '2020-10-05',
    active: false,
  },
  {
    id: '35',
    name: 'Product 35',
    description: 'Description for product 35',
    price: 125,
    stock: 75,
    category: 'Clothing',
    availableSince: '2020-11-06',
    active: true,
  },
  {
    id: '36',
    name: 'Product 36',
    description: 'Description for product 36',
    price: 93,
    stock: 71,
    category: 'Home Appliances',
    availableSince: '2020-12-07',
    active: false,
  },
  {
    id: '37',
    name: 'Product 37',
    description: 'Description for product 37',
    price: 238,
    stock: 79,
    category: 'Electronics',
    availableSince: '2020-01-08',
    active: false,
  },
  {
    id: '38',
    name: 'Product 38',
    description: 'Description for product 38',
    price: 498,
    stock: 38,
    category: 'Books',
    availableSince: '2020-02-09',
    active: false,
  },
  {
    id: '39',
    name: 'Product 39',
    description: 'Description for product 39',
    price: 344,
    stock: 54,
    category: 'Clothing',
    availableSince: '2020-03-10',
    active: false,
  },
  {
    id: '40',
    name: 'Product 40',
    description: 'Description for product 40',
    price: 481,
    stock: 34,
    category: 'Home Appliances',
    availableSince: '2020-04-11',
    active: false,
  },
  {
    id: '41',
    name: 'Product 41',
    description: 'Description for product 41',
    price: 85,
    stock: 29,
    category: 'Electronics',
    availableSince: '2020-05-12',
    active: true,
  },
  {
    id: '42',
    name: 'Product 42',
    description: 'Description for product 42',
    price: 4,
    stock: 92,
    category: 'Books',
    availableSince: '2020-06-13',
    active: false,
  },
  {
    id: '43',
    name: 'Product 43',
    description: 'Description for product 43',
    price: 276,
    stock: 71,
    category: 'Clothing',
    availableSince: '2020-07-14',
    active: true,
  },
  {
    id: '44',
    name: 'Product 44',
    description: 'Description for product 44',
    price: 118,
    stock: 69,
    category: 'Home Appliances',
    availableSince: '2020-08-15',
    active: true,
  },
  {
    id: '45',
    name: 'Product 45',
    description: 'Description for product 45',
    price: 421,
    stock: 71,
    category: 'Electronics',
    availableSince: '2020-09-16',
    active: true,
  },
  {
    id: '46',
    name: 'Product 46',
    description: 'Description for product 46',
    price: 10,
    stock: 4,
    category: 'Books',
    availableSince: '2020-10-17',
    active: true,
  },
  {
    id: '47',
    name: 'Product 47',
    description: 'Description for product 47',
    price: 314,
    stock: 24,
    category: 'Clothing',
    availableSince: '2020-11-18',
    active: true,
  },
  {
    id: '48',
    name: 'Product 48',
    description: 'Description for product 48',
    price: 199,
    stock: 84,
    category: 'Home Appliances',
    availableSince: '2020-12-19',
    active: false,
  },
  {
    id: '49',
    name: 'Product 49',
    description: 'Description for product 49',
    price: 352,
    stock: 8,
    category: 'Electronics',
    availableSince: '2020-01-20',
    active: true,
  },
  {
    id: '50',
    name: 'Product 50',
    description: 'Description for product 50',
    price: 204,
    stock: 21,
    category: 'Books',
    availableSince: '2020-02-21',
    active: false,
  },
  {
    id: '51',
    name: 'Product 51',
    description: 'Description for product 51',
    price: 449,
    stock: 41,
    category: 'Clothing',
    availableSince: '2020-03-22',
    active: false,
  },
  {
    id: '52',
    name: 'Product 52',
    description: 'Description for product 52',
    price: 250,
    stock: 8,
    category: 'Home Appliances',
    availableSince: '2020-04-23',
    active: true,
  },
  {
    id: '53',
    name: 'Product 53',
    description: 'Description for product 53',
    price: 190,
    stock: 94,
    category: 'Electronics',
    availableSince: '2020-05-24',
    active: false,
  },
  {
    id: '54',
    name: 'Product 54',
    description: 'Description for product 54',
    price: 415,
    stock: 86,
    category: 'Books',
    availableSince: '2020-06-25',
    active: true,
  },
  {
    id: '55',
    name: 'Product 55',
    description: 'Description for product 55',
    price: 312,
    stock: 25,
    category: 'Clothing',
    availableSince: '2020-07-26',
    active: false,
  },
  {
    id: '56',
    name: 'Product 56',
    description: 'Description for product 56',
    price: 259,
    stock: 6,
    category: 'Home Appliances',
    availableSince: '2020-08-27',
    active: true,
  },
  {
    id: '57',
    name: 'Product 57',
    description: 'Description for product 57',
    price: 126,
    stock: 88,
    category: 'Electronics',
    availableSince: '2020-08-31',
    active: false,
  },
  {
    id: '58',
    name: 'Product 58',
    description: 'Description for product 58',
    price: 101,
    stock: 37,
    category: 'Books',
    availableSince: '2020-10-01',
    active: true,
  },
  {
    id: '59',
    name: 'Product 59',
    description: 'Description for product 59',
    price: 405,
    stock: 73,
    category: 'Clothing',
    availableSince: '2020-11-02',
    active: false,
  },
  {
    id: '60',
    name: 'Product 60',
    description: 'Description for product 60',
    price: 11,
    stock: 74,
    category: 'Home Appliances',
    availableSince: '2020-12-03',
    active: false,
  },
  {
    id: '61',
    name: 'Product 61',
    description: 'Description for product 61',
    price: 379,
    stock: 34,
    category: 'Electronics',
    availableSince: '2020-01-04',
    active: false,
  },
  {
    id: '62',
    name: 'Product 62',
    description: 'Description for product 62',
    price: 136,
    stock: 33,
    category: 'Books',
    availableSince: '2020-02-05',
    active: true,
  },
  {
    id: '63',
    name: 'Product 63',
    description: 'Description for product 63',
    price: 44,
    stock: 85,
    category: 'Clothing',
    availableSince: '2020-03-06',
    active: false,
  },
  {
    id: '64',
    name: 'Product 64',
    description: 'Description for product 64',
    price: 20,
    stock: 43,
    category: 'Home Appliances',
    availableSince: '2020-04-07',
    active: false,
  },
  {
    id: '65',
    name: 'Product 65',
    description: 'Description for product 65',
    price: 395,
    stock: 79,
    category: 'Electronics',
    availableSince: '2020-05-08',
    active: false,
  },
  {
    id: '66',
    name: 'Product 66',
    description: 'Description for product 66',
    price: 123,
    stock: 85,
    category: 'Books',
    availableSince: '2020-06-09',
    active: true,
  },
  {
    id: '67',
    name: 'Product 67',
    description: 'Description for product 67',
    price: 330,
    stock: 20,
    category: 'Clothing',
    availableSince: '2020-07-10',
    active: false,
  },
  {
    id: '68',
    name: 'Product 68',
    description: 'Description for product 68',
    price: 220,
    stock: 58,
    category: 'Home Appliances',
    availableSince: '2020-08-11',
    active: false,
  },
  {
    id: '69',
    name: 'Product 69',
    description: 'Description for product 69',
    price: 120,
    stock: 19,
    category: 'Electronics',
    availableSince: '2020-09-12',
    active: false,
  },
  {
    id: '70',
    name: 'Product 70',
    description: 'Description for product 70',
    price: 313,
    stock: 30,
    category: 'Books',
    availableSince: '2020-10-13',
    active: false,
  },
  {
    id: '71',
    name: 'Product 71',
    description: 'Description for product 71',
    price: 383,
    stock: 23,
    category: 'Clothing',
    availableSince: '2020-11-14',
    active: true,
  },
  {
    id: '72',
    name: 'Product 72',
    description: 'Description for product 72',
    price: 45,
    stock: 70,
    category: 'Home Appliances',
    availableSince: '2020-12-15',
    active: true,
  },
  {
    id: '73',
    name: 'Product 73',
    description: 'Description for product 73',
    price: 433,
    stock: 72,
    category: 'Electronics',
    availableSince: '2020-01-16',
    active: false,
  },
  {
    id: '74',
    name: 'Product 74',
    description: 'Description for product 74',
    price: 414,
    stock: 97,
    category: 'Books',
    availableSince: '2020-02-17',
    active: true,
  },
  {
    id: '75',
    name: 'Product 75',
    description: 'Description for product 75',
    price: 369,
    stock: 42,
    category: 'Clothing',
    availableSince: '2020-03-18',
    active: true,
  },
  {
    id: '76',
    name: 'Product 76',
    description: 'Description for product 76',
    price: 256,
    stock: 31,
    category: 'Home Appliances',
    availableSince: '2020-04-19',
    active: false,
  },
  {
    id: '77',
    name: 'Product 77',
    description: 'Description for product 77',
    price: 372,
    stock: 92,
    category: 'Electronics',
    availableSince: '2020-05-20',
    active: false,
  },
  {
    id: '78',
    name: 'Product 78',
    description: 'Description for product 78',
    price: 145,
    stock: 7,
    category: 'Books',
    availableSince: '2020-06-21',
    active: false,
  },
  {
    id: '79',
    name: 'Product 79',
    description: 'Description for product 79',
    price: 391,
    stock: 52,
    category: 'Clothing',
    availableSince: '2020-07-22',
    active: true,
  },
  {
    id: '80',
    name: 'Product 80',
    description: 'Description for product 80',
    price: 2,
    stock: 25,
    category: 'Home Appliances',
    availableSince: '2020-08-23',
    active: false,
  },
  {
    id: '81',
    name: 'Product 81',
    description: 'Description for product 81',
    price: 106,
    stock: 81,
    category: 'Electronics',
    availableSince: '2020-09-24',
    active: true,
  },
  {
    id: '82',
    name: 'Product 82',
    description: 'Description for product 82',
    price: 37,
    stock: 80,
    category: 'Books',
    availableSince: '2020-10-25',
    active: true,
  },
  {
    id: '83',
    name: 'Product 83',
    description: 'Description for product 83',
    price: 308,
    stock: 12,
    category: 'Clothing',
    availableSince: '2020-11-26',
    active: false,
  },
  {
    id: '84',
    name: 'Product 84',
    description: 'Description for product 84',
    price: 226,
    stock: 81,
    category: 'Home Appliances',
    availableSince: '2020-12-27',
    active: true,
  },
  {
    id: '85',
    name: 'Product 85',
    description: 'Description for product 85',
    price: 330,
    stock: 57,
    category: 'Electronics',
    availableSince: '2019-12-31',
    active: true,
  },
  {
    id: '86',
    name: 'Product 86',
    description: 'Description for product 86',
    price: 87,
    stock: 97,
    category: 'Books',
    availableSince: '2020-02-01',
    active: true,
  },
  {
    id: '87',
    name: 'Product 87',
    description: 'Description for product 87',
    price: 197,
    stock: 35,
    category: 'Clothing',
    availableSince: '2020-03-02',
    active: false,
  },
  {
    id: '88',
    name: 'Product 88',
    description: 'Description for product 88',
    price: 167,
    stock: 44,
    category: 'Home Appliances',
    availableSince: '2020-04-03',
    active: false,
  },
  {
    id: '89',
    name: 'Product 89',
    description: 'Description for product 89',
    price: 435,
    stock: 61,
    category: 'Electronics',
    availableSince: '2020-05-04',
    active: false,
  },
  {
    id: '90',
    name: 'Product 90',
    description: 'Description for product 90',
    price: 236,
    stock: 21,
    category: 'Books',
    availableSince: '2020-06-05',
    active: true,
  },
  {
    id: '91',
    name: 'Product 91',
    description: 'Description for product 91',
    price: 163,
    stock: 63,
    category: 'Clothing',
    availableSince: '2020-07-06',
    active: false,
  },
  {
    id: '92',
    name: 'Product 92',
    description: 'Description for product 92',
    price: 58,
    stock: 62,
    category: 'Home Appliances',
    availableSince: '2020-08-07',
    active: false,
  },
  {
    id: '93',
    name: 'Product 93',
    description: 'Description for product 93',
    price: 454,
    stock: 1,
    category: 'Electronics',
    availableSince: '2020-09-08',
    active: false,
  },
  {
    id: '94',
    name: 'Product 94',
    description: 'Description for product 94',
    price: 274,
    stock: 39,
    category: 'Books',
    availableSince: '2020-10-09',
    active: true,
  },
  {
    id: '95',
    name: 'Product 95',
    description: 'Description for product 95',
    price: 468,
    stock: 9,
    category: 'Clothing',
    availableSince: '2020-11-10',
    active: false,
  },
  {
    id: '96',
    name: 'Product 96',
    description: 'Description for product 96',
    price: 147,
    stock: 70,
    category: 'Home Appliances',
    availableSince: '2020-12-11',
    active: false,
  },
  {
    id: '97',
    name: 'Product 97',
    description: 'Description for product 97',
    price: 53,
    stock: 78,
    category: 'Electronics',
    availableSince: '2020-01-12',
    active: false,
  },
  {
    id: '98',
    name: 'Product 98',
    description: 'Description for product 98',
    price: 9,
    stock: 58,
    category: 'Books',
    availableSince: '2020-02-13',
    active: true,
  },
  {
    id: '99',
    name: 'Product 99',
    description: 'Description for product 99',
    price: 125,
    stock: 40,
    category: 'Clothing',
    availableSince: '2020-03-14',
    active: true,
  },
  {
    id: '100',
    name: 'Product 100',
    description: 'Description for product 100',
    price: 358,
    stock: 16,
    category: 'Home Appliances',
    availableSince: '2020-04-15',
    active: true,
  },
];
